name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      # Install dependencies in root
      - name: Install root dependencies
        run: npm install

      # Install dependencies in frontend
      - name: Install frontend dependencies
        run: cd frontend && npm install

      # Compile contracts
      - name: Compile contracts
        run: npm run compile

      # Run tests
      - name: Run tests
        run: npm test
